var index0 = []
/**
name: "",
en: "",
book: "phb" "dmg"
page: "", (page number in book)
ru: "",
reference: "", (See ...)
link:"contents/dmg8_conditions.html#", (URL)
sub:""     */
var _index = [
    { id:"ability_damaged", name:"Урон характеристике", en:"Ability Damaged",book:"dmg",page:"300",reference: "",link:"contents/dmg8_conditions.html#ability_damaged",sub:"" },
    { id:"ability_drained", name:"Откачана характеристика", en:"Ability Drained",book:"dmg",page:"300",reference: "",link:"contents/dmg8_conditions.html#ability_drained",sub:"" },
    { id:"blinded", name:"Слепой", en:"Blinded",book:"dmg",page:"300",reference: "",link:"contents/dmg8_conditions.html#blinded",sub:"" },
    { id:"blown_away", name:"Сбит ветром", en:"Blown Away",book:"dmg",page:"300",reference: "",link:"contents/dmg8_conditions.html#blown_away",sub:"" },
    { id:"checked", name:"Задержан", en:"Checked",book:"dmg",page:"300",reference: "",link:"contents/dmg8_conditions.html#checked",sub:"" },
    { id:"confused", name:"Смущен", en:"Confused",book:"dmg",page:"300",reference: "",link:"contents/dmg8_conditions.html#confused",sub:"" },
    { id:"cowering", name:"Съежившийся", en:"Cowering",book:"dmg",page:"300",reference: "",link:"contents/dmg8_conditions.html#cowering",sub:"" },
    { id:"dazed", name:"Изумлен", en:"Dazed",book:"dmg",page:"300",reference: "",link:"contents/dmg8_conditions.html#dazed",sub:"" },
    { id:"dazzled", name:"Ослеплен (вспышкой)", en:"Dazzled",book:"dmg",page:"300",reference: "",link:"contents/dmg8_conditions.html#dazzled",sub:"" },
    { id:"dead", name:"Мертв", en:"Dead",book:"dmg",page:"300",reference: "",link:"contents/dmg8_conditions.html#dead",sub:"" },
    { id:"deafened", name:"Глухой", en:"Deafened",book:"dmg",page:"300",reference: "",link:"contents/dmg8_conditions.html#deafened",sub:"" },
    { id:"disabled", name:"Недееспособный", en:"Disabled",book:"dmg",page:"300",reference: "",link:"contents/dmg8_conditions.html#disabled",sub:"" },
    { id:"dying", name:"Умирающий", en:"Dying",book:"dmg",page:"300",reference: "",link:"contents/dmg8_conditions.html#dying",sub:"" },
    { id:"energy_drained", name:"Откачана энергия", en:"Energy Drained",book:"dmg",page:"300",reference: "",link:"contents/dmg8_conditions.html#energy_drained",sub:"" },
    { id:"entangled", name:"Опутан", en:"Entangled",book:"dmg",page:"300",reference: "",link:"contents/dmg8_conditions.html#entangled",sub:"" },
    { id:"exhausted", name:"Обессилен", en:"Exhausted",book:"dmg",page:"300",reference: "",link:"contents/dmg8_conditions.html#exhausted",sub:"" },
    { id:"fascinated", name:"Очарованный", en:"Fascinated",book:"dmg",page:"300",reference: "",link:"contents/dmg8_conditions.html#fascinated",sub:"" },
    { id:"fatigued", name:"Уставший", en:"Fatigued",book:"dmg",page:"301",reference: "",link:"contents/dmg8_conditions.html#fatigued",sub:"" },
    { id:"flat_footed", name:"Неподготовленный", en:"Flat-Footed",book:"dmg",page:"301",reference: "",link:"contents/dmg8_conditions.html#flat_footed",sub:"" },
    { id:"frightened", name:"Испуган", en:"Frightened",book:"dmg",page:"301",reference: "",link:"contents/dmg8_conditions.html#frightened",sub:"" },
    { id:"grappling", name:"Захвачен", en:"Grappling",book:"dmg",page:"301",reference: "",link:"contents/dmg8_conditions.html#grappling",sub:"" },
    { id:"helpless", name:"Беспомощный", en:"Helpless",book:"dmg",page:"301",reference: "",link:"contents/dmg8_conditions.html#helpless",sub:"" },
    { id:"incorporeal", name:"Бестелесный", en:"Incorporeal",book:"dmg",page:"301",reference: "",link:"contents/dmg8_conditions.html#incorporeal",sub:"" },
    { id:"invisible", name:"Невидимый", en:"Invisible",book:"dmg",page:"301",reference: "",link:"contents/dmg8_conditions.html#invisible",sub:"" },
    { id:"knocked_down", name:"Опрокинут", en:"Knocked Down",book:"dmg",page:"301",reference: "",link:"contents/dmg8_conditions.html#knocked_down",sub:"" },
    { id:"nauseated", name:"Тошнота", en:"Nauseated",book:"dmg",page:"301",reference: "",link:"contents/dmg8_conditions.html#nauseated",sub:"" },
    { id:"panicked", name:"Паникующий", en:"Panicked",book:"dmg",page:"301",reference: "",link:"contents/dmg8_conditions.html#panicked",sub:"" },
    { id:"paralyzed", name:"Парализован", en:"Paralyzed",book:"dmg",page:"301",reference: "",link:"contents/dmg8_conditions.html#paralyzed",sub:"" },
    { id:"petrified", name:"Окаменевший", en:"Petrified",book:"dmg",page:"301",reference: "",link:"contents/dmg8_conditions.html#petrified",sub:"" },
    { id:"pinned", name:"Удерживаемый", en:"Pinned",book:"dmg",page:"301",reference: "",link:"contents/dmg8_conditions.html#pinned",sub:"" },
    { id:"prone", name:"Сбит с ног", en:"Prone",book:"dmg",page:"301",reference: "",link:"contents/dmg8_conditions.html#prone",sub:"" },
    { id:"shaken", name:"Потрясен", en:"Shaken",book:"dmg",page:"301",reference: "",link:"contents/dmg8_conditions.html#shaken",sub:"" },
    { id:"sickened", name:"Болен", en:"Sickened",book:"dmg",page:"301",reference: "",link:"contents/dmg8_conditions.html#sickened",sub:"" },
    { id:"stable", name:"Стабилен", en:"Stable",book:"dmg",page:"301",reference: "",link:"contents/dmg8_conditions.html#stable",sub:"" },
    { id:"staggered", name:"Ошеломленный", en:"Staggered",book:"dmg",page:"301",reference: "",link:"contents/dmg8_conditions.html#staggered",sub:"" },
    { id:"stunned", name:"Оглушен", en:"Stunned",book:"dmg",page:"301",reference: "",link:"contents/dmg8_conditions.html#stunned",sub:"" },
    { id:"turned", name:"Изгнан", en:"Turned",book:"dmg",page:"301",reference: "",link:"contents/dmg8_conditions.html#turned",sub:"" },
    { id:"unconscious", name:"Без сознания", en:"Unconscious",book:"dmg",page:"301",reference: "",link:"contents/dmg8_conditions.html#unconscious",sub:"" },
    { id:"extraordinary_abilities", name:"Экстраординарные способности", en:"Extraordinary Abilities",book:"dmg",page:"289",reference: "",link:"contents/dmg8_abilities.html#extraordinary_abilities",sub:"" },
    { id:"supernatural_abilities", name:"Сверхъестественные способности", en:"Supernatural Abilities",book:"dmg",page:"289",reference: "",link:"contents/dmg8_abilities.html#supernatural_abilities",sub:"" },
    { id:"spell_like_abilities", name:"Заклинательные способности", en:"Spell-like Abilities",book:"dmg",page:"289",reference: "",link:"contents/dmg8_abilities.html#spell_like_abilities",sub:"" },
    { id:"ability_score_loss", name:"Уменьшение характеристики", en:"Ability Score Loss",book:"dmg",page:"289",reference: "",link:"contents/dmg8_abilities.html#ability_score_loss",sub:"" },
    { id:"alternate_form", name:"Альтернативная форма", en:"Alternate Form",book:"dmg",page:"?",reference: "",link:"contents/dmg8_abilities.html#alternate_form",sub:"" },
    { id:"antimagic", name:"Антимагия", en:"Antimagic",book:"dmg",page:"290",reference: "",link:"contents/dmg8_abilities.html#antimagic",sub:"" },
    { id:"breath_weapon", name:"Оружие дыхания", en:"Breath Weapon",book:"dmg",page:"291",reference: "",link:"contents/dmg8_abilities.html#breath_weapon",sub:"" },
    { id:"change_shape", name:"Смена формы", en:"Change Shape",book:"dmg",page:"?",reference: "",link:"contents/dmg8_abilities.html#change_shape",sub:"" },
    { id:"cold_immunity", name:"Иммунитет к холоду", en:"Cold Immunity",book:"dmg",page:"291",reference: "",link:"contents/dmg8_abilities.html#cold_immunity",sub:"" },
    { id:"constrict", name:"Сжимает", en:"Constrict",book:"dmg",page:"?",reference: "",link:"contents/dmg8_abilities.html#constrict",sub:"" },
    { id:"damage_reduction", name:"Снижение урона", en:"Damage Reduction",book:"dmg",page:"291",reference: "",link:"contents/dmg8_abilities.html#damage_reduction",sub:"" },
    { id:"darkvision", name:"Темновидение", en:"Darkvision",book:"dmg",page:"292",reference: "",link:"contents/dmg8_abilities.html#darkvision",sub:"" },
    { id:"etherealness", name:"Эфирность", en:"Etherealness",book:"dmg",page:"293",reference: "",link:"contents/dmg8_abilities.html#etherealness",sub:"" },
    { id:"", name:"", en:"",book:"dmg",page:"",reference: "",link:"contents/dmg8_abilities.html#",sub:"" },
    { id:"", name:"", en:"",book:"dmg",page:"",reference: "",link:"contents/dmg8_abilities.html#",sub:"" },
    { id:"", name:"", en:"",book:"dmg",page:"",reference: "",link:"contents/dmg8_abilities.html#",sub:"" },
    { id:"", name:"", en:"",book:"dmg",page:"",reference: "",link:"contents/dmg8_abilities.html#",sub:"" },
    { id:"", name:"", en:"",book:"dmg",page:"",reference: "",link:"contents/dmg8_abilities.html#",sub:"" },
    { id:"tremorsense", name:"Чувство вибрации", en:"Tremorsense",book:"dmg",page:"299",reference: "",link:"contents/dmg8_abilities.html#",sub:"" },
    { id:"turn_resistance", name:"Сопротивляемость изгнанию", en:"Turn Resistance",book:"dmg",page:"299",reference: "",link:"contents/dmg8_abilities.html#turn_resistance",sub:"" },
    { id:"vulnerability_to_energy", name:"Уязвимость к энергии", en:"Vulnerability to Energy",book:"dmg",page:"?",reference: "",link:"contents/dmg8_abilities.html#vulnerability_to_energy",sub:"" },
];
