// ["racial-traits","ability-score-increase"]

var index0 = []
/**
name: "",
en: "",
page: "", (page number in book)
ru: "",
reference: "", (See ...)
link:"", (URL)
sub:""     */

index = [{items:[
    {id:"0-level-spell",name: "0-level spell",en: "A spell of the lowest possible level. Arcane spellcasters often call  their  0-level  spells  “cantrips,”  and divine spellcasters often call them “orisons.”",page: "181, 183, 189, 192",link:"",
        sub: [{id:"0-level-spell-in-spellbook ",name: "in spellbook ",en: "",page: "179",link:""}]},
    {id:"5-foot-step",name: "5-foot step",en: "A small position adjustment that does not count as an action. Usually (but not always), a 5-foot step is permitted at any point in the round (such as before or after a full-round action, between attacks in a full attack, between a standard action and a move action, or between two move actions). You can’t take a 5-foot step in the same round that you move any distance. You can’t take a 5-foot step if your movement is hampered, such as into a square of difficult terrain, in darkness, or when blinded. Taking a 5-foot step does not provoke an attack of opportunity, even if you move out of a threatened square.",page: "138, 144, 145",runame: "1,5 метровый шаг",link:""},
    {id:"aberration",name: "Аberration (type)",runame: "Необычный (тип)",link:""},
    {id:"",name: "abilities and spellcasters ",page: "7",link:""},
    {id:"ability",name: "ability",en: "One of the six basic character qualities: Strength (Str), Dexterity (Dex), Constitution (Con), Intelligence (Int), Wisdom (Wis), and Charisma (Cha). See ability score.",runame: "способность",reference:"ability score",link:"contents/phb1_Abilities.html"},
    {id:"",name: "Ability Focus",runame: "Фокусирование на Способности‫٭‬ ",link:""},
    {id:"",name: "ability check",en: "A check of 1d20 + the appropriate ability modifier.",page: "65, 66",runame: "проверка параметра",link:""},
    {id:"",name: "ability damage",en: "A temporary loss of 1 or more ability score points. Lost points return at a rate of 1 point per day unless noted otherwise by the condition dealing the damage. A character with Strength 0 falls to the ground and is helpless. A character with Dexterity 0 is paralyzed. A character with Constitution 0 is dead. A Character with Intelligence, Wisdom, or Charisma 0 is unconscious.",page: "134",runame: "повреждение параметра",link:"",
        sub: [{id:"",name: "healing",page: "146",link:""}]},
    {id:"",name: "ability decrease",en: "A decrease in an ability score that ends when the condition causing it does.",runame: "понижение параметра",link:""},
    {id:"",name: "ability drain",en: "A permanent loss of 1 or more ability score points. The character can only regain these points through magical means. A character with Strength 0 falls to the ground and is helpless. A character with Dexterity 0 is paralyzed. A character with Constitution 0 is dead. A Character with Intelligence, Wisdom, or Charisma 0 is unconscious.",page: "10, 145",runame: "высасывание параметра",link:"",
        sub: [{id:"",name: "restoring",page: "272",link:""}]},
    {id:"",name: "ability modifier",en: "The bonus or penalty associated with a particular ability score. Ability modifiers apply to die rolls for character actions involving the corresponding abilities.",page: "7",runame: "модификатор параметра",link:""},
    {id:"ability-score",name: "ability score",en: "The numeric rating of one of the six character abilities (see ability). Some creatures lack certain ability scores; others cannot be rated in particular abilities.",page: "7",runame: "показатель параметра",link:"",
        sub: [{id:"",name: "changing",page: "10",link:""},
            {id:"",name: "generating",page: "10",link:""},
            {id:"",name: "racial adjustments",page: "11, 12",link:""},
            {id:"",name: "rerolling",page: "8",link:""}]},
    {id:"",name: "abjuration (school)",page: "57, 172",runame: "защита (школа магии)",link:""},
    {id:"",name: "abundant step (monk) ",page: "42",link:""},
    {id:"",name: "Abyss ",runame: "Абисс",link:""},
    {id:"",name: "AC bonus (monk) ",page: "40",link:""},
    {id:"",name: "Acrobatic ",page: "89",runame: "Акробатический",link:""},
    {id:"",name: "action",en: "A character activity. Actions are divided into the fol-lowing categories, according to the time required to perform them (from most time required to least): full-round actions, standard actions, move actions, and free actions.",runame: "действие",link:""},
    {id:"",name: "actions in combat",page: "138",link:""},
    {id:"",name: "activate magic item (action) ",page: "142",runame: "активация магического предмета (действие)",link:""},
    {id:"",name: "Acheron",runame: "Ахерон",link:""},
    {id:"",name: "adamantine",runame: "адамантин",link:""},
    {id:"",name: "adept (NPC class) ",runame: "адепт (класс НИП)",link:""},
    {id:"",name: "adjacent",en: "In a square that shares a border or a corner with a designated square. Each square is adjacent to eight other squares on the board.",runame: "смежная (клетка поля боя)",link:""},
    {id:"",name: "adjucating",runame: "корректирование",link:""},
    {id:"",name: "adventuring party",en: "A  group  of  characters  who  adventure together. An adventuring party is composed of player characters plus any followers, familiars, animal companions, associates, cohorts, or hirelings they might have.",runame: "группа авантюристов",link:""},
    {id:"",name: "advancing a level",page: "58",link:"",
        sub: [{id:"",name: "for multiclass characters",page: "60",link:""}]},
    {id:"",name: "adventuring gear",page: "126",link:""},
    {id:"",name: "age (of characters)",page: "109",link:""},
    {id:"",name: "Agile",page: "89",runame: "Ловкий",link:""},
    {id:"",name: "aging effects",page: "109",runame: "эффект возраста",link:""},
    {id:"",name: "aid another (skill check)",page: "65",runame: "помощь другому",link:""},
    {id:"",name: "aid another (special attack)",page: "154",runame: "помощь другому",link:""},
    {id:"",name: "aiming a spell",page: "175",runame: "прицеливание заклинания",link:""},
    {id:"",name: "Air domain",page: "185",runame: "Воздух (сфера)",link:""},
    {id:"",name: "Air (subtype)",runame: "Воздушный (подтип)",link:""},
    {id:"",name: "аerial movement",runame: "воздушное передвижение",link:""},
    {id:"",name: "аir lack",runame: "нехватка воздуха",link:""},
    {id:"",name: "alchemical items",page: "128",link:""},
    {id:"",name: "Alertness",page: "89",runame: "Настороженность",link:""},
    {id:"",name: "alignment",en: "One of the nine descriptors of morality for intelligent creatures: lawful good (LG), neutral good (NG), chaotic good (CG), lawful neutral (LN), neutral (N), chaotic neutral (CN), lawful evil (LE), neutral evil (NE), and chaotic evil (CE). ally: A creature friendly to you. In most cases, references to “allies” include yourself.",page: "103",runame: "мировоззрение",link:"",
        sub: [{id:"",name: "for classes",page: "23",link:""},
            {id:"",name: "of clerics ",page: "31",link:""},
            {id:"",name: "of deities",page: "106",link:""},
            {id:"",name: "domains",page: "32",link:""},
            {id:"",name: "and spells",page: "33,35",link:""}]},
    {id:"",name: "ally",runame: "союзник",link:""},
    {id:"",name: "ammunition",page: "113",link:""},
    {id:"",name: "Angel (subtype)",runame: "Ангел (подтип)",link:""},
    {id:"",name: "Animal (type)",en: "A type of creature that includes all natural animals, dire animals, giant animals, and some other nonmagical vertebrate creatures (see the Monster Manual). Animals always have an Intelligence score of 1 or 2.",link:""},
    {id:"",name: "Animal Affinity",page: "89",runame: "Близость к Животным",link:""},
    {id:"",name: "animal companion (druid) ",page: "35",link:""},
    {id:"",name: "animal companion (ranger) ",page: "48",link:""},
    {id:"",name: "Animal domain",page: "186",runame: "Животные (сфера)",link:""},
    {id:"",name: "Appraise",page: "67",runame: "Оценка",link:""},
    {id:"",name: "Arborea",runame: "Арборея",link:""},
    {id:"",name: "Arcadia",runame: "Аркадия",link:""},
    {id:"",name: "arcane magical writings",page: "178",link:""},
    {id:"",name: "arcane spell failure",en: "The chance that a spell fails and is cast to no effect because the caster’s  ability  to  use  a  somatic component was hampered by armor. Bards can ignore the arcane spell failure chance for light armor when casting bard spells.",page: "56, 122",runame: "провал тайного заклинания",link:""},
    {id:"",name: "arcane spells",en: "Arcane spells involve the direct manipulation of mystic energies. Bards, sorcerers, and wizards cast arcane spells.",page: "177",runame: "тайное заклинание",link:"",
        sub: [{id:"",name: "and armor",page: "56",link:""}]},
    {id:"",name: "area (of a spell)",page: "175",link:""},
    {id:"",name: "“armed“ unarmed attacks",page: "139",link:""},
    {id:"",name: "armor",page: "122",link:"",
        sub: [{id:"",name: "barding",page: "131",link:""},
            {id:"",name: "encumbrance",page: "161",link:""},
            {id:"",name: "getting into and out of",page: "123",link:""},
            {id:"",name: "for unusual creatures",page: "123",link:""}]},
    {id:"",name: "armor bonus",en: "A bonus to Armor Class granted by armor or by a spell or magical effect that mimics armor. Armor bonuses stack with all other bonuses to Armor Class (even with natural armor bonuses) except other armor bonuses. Magic armor typically grants an enhancement bonus to the armor’s armor bonus, which has the effect of increasing the armor’s overall bonus. An armor bonus granted by a spell or magic item typically takes the form of an invisible, tangible field of force around the recipient. An armor bonus doesn’t apply against touch attacks, except for armor bonuses granted by force effects (such as the mage armor spell) which apply against incorporeal touch attacks, such as that of a shadow.",page: "122",runame: "бонус доспеха",link:""},
    {id:"",name: "Armor Class (AC)",en: "A number representing a creature’s ability to avoid being hit in combat. An opponent’s attack roll must equal or exceed the target creature’s Armor Class to hit it. Armor Class = 10 + all modifiers that apply (typically armor bonus, shield bonus, Dexterity modifier, and size modifier).",page: "134",runame: "Класс Доспеха (КД)",link:"",
        sub: [{id:"",name: "modifiers",page: "151",link:""},
            {id:"",name: "of objects",page: "166",link:""}]},
    {id:"",name: "armor check penalty",page: "122",runame: "штраф проверки из-за доспеха",link:""},
    {id:"",name: "Armor Proficiency",page: "89, 122",runame: "Квалификация в Доспехах",link:""},
    {id:"",name: "Aquatic (subtype)",runame: "Водяной (подтип)",link:""},
    {id:"",name: "Archon (subtype)",runame: "Архон (подтип)",link:""},
    {id:"",name: "aristocrat",runame: "аристократ (клас НИП)",link:""},
    {id:"",name: "аrtifact",en: "A magic item of incredible power. Some spells do not function when targeted on an artifact.",runame: "артефакт",link:""},
    {id:"",name: "Astral Plane",en: "An open, weightless plane that connects with all other planes of existence and is used for transportation among them (and is thus described as a transitive plane, like the Ethereal Plane and the Plane of Shadow). Certain spells (such as astral projection) allow access to this plane.",page: "171, 173, 201, 213",runame: "Астральный план",link:""},
    {id:"",name: "Athletic",page: "89",runame: "Атлетичный",link:""},
    {id:"",name: "attack (action)",en: "Any of numerous actions intended to harm, disable, or neutralize an opponent. The outcome of an attack is determined by an attack roll.",page: "139",runame: "атака (действие)",link:""},
    {id:"",name: "attack bonus",page: "134",link:""},
]}];
