_skills = [ // classes: [ "bbn", "brd", "clr", "drd", "ftr", "mnk", "pal", "rgr", "rog", "sor", "wiz"]
    {id: "appraise", name:"Оценка",en:"Appraise",untrained:true,ac_penalty:0,ability:"int",classes:["brd","rog"]},
    {id: "balance", name:"Балансирование",en:"Balance",untrained:true,ac_penalty:1,ability:"dex",classes:["brd", "mnk", "rog"]},
    {id: "bluff", name:"Блеф",en:"Bluff",untrained:true,ac_penalty:0,ability:"cha",classes:["brd","rog", "sor"]},
    {id: "climb", name:"Лазание",en:"Climb",untrained:true,ac_penalty:1,ability:"str",classes:["bbn", "brd", "ftr", "mnk", "rgr", "rog"]},
    {id: "concentration", name:"Концентрация",en:"Concentration",untrained:true,ac_penalty:0,ability:"con",classes:["brd", "clr", "drd", "mnk", "pal", "rgr", "sor", "wiz"]},
    {id: "craft", name:"Ремесло",en:"Craft",untrained:true,ac_penalty:0,ability:"int",classes:["bbn", "brd", "clr", "drd", "ftr", "mnk", "pal", "rgr", "rog", "sor", "wiz"]},
    {id: "decipher-script", name:"Расшифровка",en:"Decipher Script",untrained:false,ac_penalty:0,ability:"int",classes:["brd","rog"]},
    {id: "diplomacy", name:"Дипломатия",en:"Diplomacy",untrained:true,ac_penalty:0,ability:"cha",classes:["brd", "clr", "drd", "mnk", "pal", "rog"]},
    {id: "disable-device", name:"Сломать Устройство",en:"Disable Device",untrained:false,ac_penalty:0,ability:"int",classes:["rog"]},
    {id: "disguise", name:"Гримировка",en:"Disguise",untrained:true,ac_penalty:0,ability:"cha",classes:["brd","rog"]},
    {id: "escape-artist", name:"Мастер Побега",en:"Escape Artist",untrained:true,ac_penalty:1,ability:"dex",classes:["brd", "mnk", "rog"]},
    {id: "forgery", name:"Подделка",en:"Forgery",untrained:true,ac_penalty:0,ability:"int",classes:["rog"]},
    {id: "gather-information", name:"Сбор Информации",en:"Gather Information",untrained:true,ac_penalty:0,ability:"cha",classes:["brd","rog"]},
    {id: "handle-animal", name:"Дрессировка",en:"Handle Animal",untrained:false,ac_penalty:0,ability:"cha",classes:["bbn", "drd", "ftr", "pal", "rgr"]},
    {id: "heal", name:"Лечение",en:"Heal",untrained:true,ac_penalty:0,ability:"wiz",classes:["clr", "drd", "pal", "rgr"]},
    {id: "hide", name:"Прятаться",en:"Hide",untrained:true,ac_penalty:1,ability:"dex",classes:["brd", "mnk", "rgr", "rog"]},
    {id: "intimidate", name:"Запугивание",en:"Intimidate",untrained:true,ac_penalty:0,ability:"cha",classes:["bbn", "ftr", "rog"]},
    {id: "jump", name:"Прыжки",en:"Jump",untrained:true,ac_penalty:1,ability:"str",classes:["bbn", "brd", "ftr", "mnk", "rgr", "rog"]},
    {id: "knowledge-arcana", name:"Знание (тайное)",en:"Knowledge (arcana)",untrained:false,ac_penalty:0,ability:"int",classes:["brd", "clr", "mnk", "sor", "wiz"]},
    {id: "knowledge-architecture-engineering", name:"Зн. (архитектура и инженерия)",en:"Kn. (architecture \& engineering)",untrained:false,ac_penalty:0,ability:"int",classes:["brd", "wiz"]},
    {id: "knowledge-dungeoneering", name:"Зн. (подземелья)",en:"Kn. (dungeoneering)",untrained:false,ac_penalty:0,ability:"int",classes:["brd", "rgr", "wiz"]},
    {id: "knowledge-geography", name:"Зн. (география)",en:"Kn. (geography)",untrained:false,ac_penalty:0,ability:"int",classes:["brd", "rgr", "wiz"]},
    {id: "knowledge-history", name:"Зн. (история)",en:"Kn. (history)",untrained:false,ac_penalty:0,ability:"int",classes:["brd", "clr", "wiz"]},
    {id: "knowledge-local", name:"Зн. (локальное)",en:"Kn. (local)",untrained:false,ac_penalty:0,ability:"int",classes:["brd", "rog", "wiz"]},
    {id: "knowledge-nature", name:"Зн. (природа)",en:"Kn. (nature)",untrained:false,ac_penalty:0,ability:"int",classes:["brd", "drd", "rgr", "wiz"]},
    {id: "knowledge-nobility-royalty", name:"Зн. (дворянство)",en:"Kn. (nobility \& royalty)",untrained:false,ac_penalty:0,ability:"int",classes:["brd", "pal", "wiz"]},
    {id: "knowledge-religion", name:"Зн. (религия)",en:"Kn. (religion)",untrained:false,ac_penalty:0,ability:"int",classes:["brd", "clr", "mnk", "pal", "wiz"]},
    {id: "knowledge-planes", name:"Зн. (измерения)",en:"Kn. (the planes)",untrained:false,ac_penalty:0,ability:"int",classes:["brd", "clr", "wiz"]},
    {id: "listen", name:"Тонкий Слух",en:"Listen",untrained:true,ac_penalty:0,ability:"wiz",classes:["bbn", "brd", "drd", "mnk", "rgr", "rog"]},
    {id: "move-silently", name:"Бесшум. Передвиж.",en:"Move Silently",untrained:true,ac_penalty:1,ability:"dex",classes:["brd", "mnk", "rgr", "rog"]},
    {id: "open-lock", name:"Взлом",en:"Open Lock",untrained:false,ac_penalty:0,ability:"dex",classes:["rog"]},
    {id: "perform", name:"Представление",en:"Perform",untrained:true,ac_penalty:0,ability:"cha",classes:["brd", "mnk", "rog"]},
    {id: "profession", name:"Профессия",en:"Profession",untrained:false,ac_penalty:0,ability:"wiz",classes:["brd", "clr", "drd", "mnk", "pal", "rgr", "rog", "sor", "wiz"]},
    {id: "ride", name:"Верховая Езда",en:"Ride",untrained:true,ac_penalty:0,ability:"dex",classes:["bbn", "drd", "ftr", "pal", "rgr"]},
    {id: "search", name:"Поиск",en:"Search",untrained:true,ac_penalty:0,ability:"int",classes:["rgr", "rog"]},
    {id: "sense-motive", name:"Чувство Правды",en:"Sense Motive",untrained:true,ac_penalty:0,ability:"wiz",classes:["brd", "mnk", "pal", "rog"]},
    {id: "sleight-of-hand", name:"Ловкость Рук",en:"Sleight of Hand",untrained:false,ac_penalty:1,ability:"dex",classes:["brd", "rog"]},
    {id: "speak-language", name:"Владение Языком",en:"Speak Language",untrained:false,ac_penalty:0,ability:"",classes:["brd"]},
    {id: "spellcraft", name:"Основы Магии",en:"Spellcraft",untrained:false,ac_penalty:0,ability:"int",classes:["brd", "clr", "drd", "sor", "wiz"]},
    {id: "spot", name:"Обнаружение",en:"Spot",untrained:true,ac_penalty:0,ability:"wiz",classes:["drd", "mnk", "rgr", "rog"]},
    {id: "survival", name:"Выживание",en:"Survival",untrained:true,ac_penalty:0,ability:"wiz",classes:["bbn", "drd", "rgr"]},
    {id: "swim", name:"Плавание",en:"Swim",untrained:true,ac_penalty:2,ability:"str",classes:["bbn", "brd", "drd", "ftr", "mnk", "rgr", "rog"]},
    {id: "tumble", name:"Акробатика",en:"Tumble",untrained:false,ac_penalty:1,ability:"dex",classes: ["brd", "mnk", "rog"]},
    {id: "use-magic-device", name:"Использ. Маг. устройс.",en:"Use Magic Device",untrained:false,ac_penalty:0,ability:"cha",classes:["brd", "rog"]},
    {id: "use-rope", name:"Использ. Веревки",en:"Use Rope",untrained:true,ac_penalty:0,ability:"dex",classes:["rgr", "rog"]}
];

module.exports = _skills
