let table_5_1 = `
<table id="skills_table" class="odd th-left">
<tr><th>Навыки</th><th>Требования</th><th>Преимущества</th></tr><tr><th colspan="3">Общие Навыки</th></tr>
<tr><td><a href="feats/acrobatic.html">Акробатика</a></td><td></td><td>+2 к Прыжкам и Акробатике</td></tr>
<tr><td><a href="feats/agile.html">Проворность</a></td><td></td><td>+2 к Балансированию и Мастеру Побега</td></tr>
<tr><td><a href="feats/alertness.html">Бдительность</a></td><td></td><td>+2 к Тонкому Слуху и Обнаружению</td></tr>
<tr><td><a href="feats/animal-affinity.html">Сходство с животным</a></td><td></td><td>+2 к Дрессировке и Верховой Езде</td></tr>
<tr><td><a href="feats/armor-proficiency-light.html">Навык ношения легкой брони</a></td><td></td><td>Отменяет штраф за ношение брони во время атаки</td></tr>
<tr><td><a href="feats/armor-proficiency-medium.html">Навык ношения средней брони</a></td><td>armor-proficiency-light</td><td>Отменяет штраф за ношение брони во время атаки</td></tr>
<tr><td><a href="feats/armor-proficiency-heavy.html">Навык ношения тяжелой брони</a></td><td>armor-proficiency-medium</td><td>Отменяет штраф за ношение брони во время атаки</td></tr>
<tr><td><a href="feats/athletic.html">Атлетический</a></td><td></td><td>+2 к Лазанию и Плаванию</td></tr>
<tr><td><a href="feats/augment-summoning.html">Усиленный призыв</a></td><td>spell-focus-conjuration</td><td>Призванное существо получает +4 к Силе и Телосложению</td></tr>
<tr><td><a href="feats/blind-fight.html">Бой вслепую</a></td><td></td><td>Повторный бросок при промахе из-за плохой видимости</td></tr>
<tr><td><a href="feats/combat-casting.html">Колдовство в бою</a></td><td></td><td>+4 к Концентрации в обороне</td></tr>
<tr><td><a href="feats/combat-expertise.html">Боевой опыт</a></td><td>Int 13</td><td>Взять до 5 очков с броска атаки и прибавить к КЗ</td></tr>
<tr><td><a href="feats/improved-disarm.html">Улучшенное обезоруживание</a></td><td>combat-expertise</td><td>+4 к попыткам обезоружить; без атаки при возможности</td></tr>
<tr><td><a href="feats/improved-feint.html">Улучшенный финт</a></td><td>combat-expertise</td><td>Ложный выпад как действие, эквивалентное передвижению</td></tr>
<tr><td><a href="feats/improved-trip.html">Улучшенная подсечка</a></td><td>combat-expertise</td><td>+4 к попытке подсечь; без атака при возможности</td></tr>
<tr><td><a href="feats/whirlwind-attack.html">Ураганная атака</a></td><td>Dex 13, combat-expertise, dodge, mobility, spring-attack, base attack bonus +4</td><td>Одна атака на каждого врага, находящегося в пределах досягаемости</td></tr>
<tr><td><a href="feats/combat-reflexes.html">Боевые рефлексы</a></td><td></td><td>Дополнительная атака при возможности</td></tr>
<tr><td><a href="feats/deceitful.html">Коварный</a></td><td></td><td>+2 к Гримировке и Подделке</td></tr>
<tr><td><a href="feats/deft-hands.html">Ловкость Рук</a></td><td></td><td>+2 к умению Ловкость Рук и Использовать Веревку</td></tr>
<tr><td><a href="feats/diligent.html">Старательный</a></td><td></td><td>+2 к Оценке и Расшифровке</td></tr>
<tr><td><a href="feats/dodge.html">Уклонение</a></td><td>Dex 13</td><td>+1 к КЗ против выбранного противника</td></tr>
<tr><td><a href="feats/mobility.html">Подвижность</a></td><td>dodge</td><td>+4 к КЗ против атак при возможности</td></tr>
<tr><td><a href="feats/spring-attack.html">Атака с ходу</a></td><td>mobility, base attack bonus +4</td><td>Возможность передвижения до и после атаки</td></tr>
<tr><td><a href="feats/endurance.html">Выносливость</a></td><td></td><td>+4 к проверкам и спасброскам против стрессового урона</td></tr>
<tr><td><a href="feats/diehard.html">Крепкий орешек</a></td><td>endurance</td><td>оставаться в сознании при –1 до –9 хитов</td></tr>
<tr><td><a href="feats/eschew-materials.html">Избегать материалы</a></td><td></td><td>Кастование без необходимости использовать матер. компонент</td></tr>
<tr><td><a href="feats/exotic-weapon-proficiency.html">Владение экзотическим оружием</a></td><td>Base attack bonus +1</td><td>Отсутствие штрафов к атакам экзотическим оружием</td></tr>
<tr><td><a href="feats/extra-turning.html">Дополнительное изгнание</a></td><td>Ability to turn or rebuke creatures</td><td>Возможность изгонять на 4 раза в день больше</td></tr>
<tr><td><a href="feats/great-fortitude.html">Исключительная стойкость</a></td><td></td><td>+2 к спасброскам Стойкости</td></tr>
<tr><td><a href="feats/improved-counterspell.html">Улучшенное антизаклинание</a></td><td></td><td>Антизаклинание против заклинания той же школы</td></tr>
<tr><td><a href="feats/improved-critical.html">Улучшенный крит. удар</a></td><td>Proficient with weapon, base attack bonus +8</td><td>Двойное значение крит. урона оружия</td></tr>
<tr><td><a href="feats/improved-initiative.html">Улучшенная инициатива</a></td><td></td><td>+4 к Инициативе</td></tr>
<tr><td><a href="feats/improved-turning.html">Улучшенное изгнание</a></td><td>Ability to turn or rebuke creatures</td><td>+1 уровень для изгнания</td></tr>
<tr><td><a href="feats/improved-unarmed-strike.html">Улучшенный безоруж. бой</a></td><td></td><td>Бой голыми руками как оружием</td></tr>
<tr><td><a href="feats/improved-grapple.html">Улучшенная борьба</a></td><td>Dex 13, improved-unarmed-strike</td><td>+4 к попытке захвата; без атаки при возможности</td></tr>
<tr><td><a href="feats/deflect-arrows.html">Отражение стрел</a></td><td>Dex 13, improved-unarmed-strike</td><td>Отразить одну дистанционную атаку за раунд</td></tr>
<tr><td><a href="feats/snatch-arrows.html">Схватывание стрел</a></td><td>Dex 15, deflect-arrows, improved-unarmed-strike</td><td>Поймать отраженную стрелу</td></tr>
<tr><td><a href="feats/stunning-fist.html">Оглушающий удар</a></td><td>Dex 13, Wis 13, improved-unarmed-strike, base attack bonus +8</td><td>Оглушить врага безоружным ударом</td></tr>
<tr><td><a href="feats/investigator.html">Исследователь</a></td><td></td><td>+2 к Сбору Информ. и Поиску</td></tr>
<tr><td><a href="feats/iron-will.html">Железная воля</a></td><td></td><td>+2 к спасброскам Воли</td></tr>
<tr><td><a href="feats/leadership.html">Лидерство</a></td><td>Character Level 6th</td><td>Привлекать военных и последователей</td></tr>
<tr><td><a href="feats/lightning-reflexes.html">Молниеносная реакция</a></td><td></td><td>+2 к спасброскам Реакции</td></tr>
<tr><td><a href="feats/magical-aptitude.html">Способность к магии</a></td><td></td><td>+2 к Основам Магии и Использ. Магического Устройства</td></tr>
<tr><td><a href="feats/martial-weapon-proficiency.html">Владение военным оружием</a></td><td></td><td>Нет штрафа к атаке военным оружием</td></tr>
<tr><td><a href="feats/mounted-combat.html">Верховой бой</a></td><td>Ride 1 rank</td><td>Сводит на нет повреждения при проверке Верховой Езды</td></tr>
<tr><td><a href="feats/mounted-archery.html">Верховая стрельба из лука</a></td><td>mounted-combat</td><td>Половина штрафа за стрельбу верхом</td></tr>
<tr><td><a href="feats/ride-by-attack.html">Верховая атака</a></td><td>mounted-combat</td><td>Передвижение до и после верховой атаки</td></tr>
<tr><td><a href="feats/spirited-charge.html">Верховая стремительная атака</a></td><td>mounted-combat, ride-by-attack</td><td>Двойной урон</td></tr>
<tr><td><a href="feats/trample.html">Растоптать</a></td><td>mounted-combat</td><td>Сбить врага с ног с помощью верхового животного</td></tr>
<tr><td><a href="feats/natural-spell.html">Естественное заклинание</a></td><td>Wis 13, Ability to use wild shape</td><td>Кастование, находясь в форме животного</td></tr>
<tr><td><a href="feats/negotiator.html">Парламентер</a></td><td></td><td>+2 к Дипломатии и Чувству Правды</td></tr>
<tr><td><a href="feats/nimble-fingers.html">Ловкие пальцы</a></td><td></td><td>+2 к Сломать Устр. и Взлом</td></tr>
<tr><td><a href="feats/persuasive.html">Убедительный</a></td><td></td><td>+2 к Блефу и Запугиванию</td></tr>
<tr><td><a href="feats/point-blank-shot.html">Выстрел в упор</a></td><td></td><td>+1 к дистанционным атакам и урону в пределах 30 футов</td></tr>
<tr><td><a href="feats/far-shot.html">Дальняя стрельба</a></td><td>point-blank-shot</td><td>Увеличивает дальность стрельбы на 50% или 100%</td></tr>
<tr><td><a href="feats/precise-shot.html">Точный выстрел</a></td><td>point-blank-shot</td><td>Без штрафа –4 при стрельбе в ближнем бою</td></tr>
<tr><td><a href="feats/rapid-shot.html">Повторный выстрел</a></td><td>Dex 13, point-blank-shot</td><td>Один дополнительный выстрел за раунд</td></tr>
<tr><td><a href="feats/manyshot.html">Одновременная стрельба</a></td><td>Dex 17, point-blank-shot, rapid-shot, base attack bonus +6</td><td>Одновременная стрельба двух и более стрел</td></tr>
<tr><td><a href="feats/shot-on-the-run.html">Стрельба на бегу</a></td><td>Dex 13, dodge, mobility, point-blank-shot, base attack bonus +4</td><td>Передвижение до и после стрельбы</td></tr>
<tr><td><a href="feats/improved-precise-shot.html">Улучш. выстрел в упор</a></td><td>Dex 19, point-blank-shot, precise-shot, base attack bonus +11</td><td>Игнорирование полных укрытий</td></tr>
<tr><td><a href="feats/power-attack.html">Могучий удар</a></td><td>Str 13</td><td>Бонус атаки перекинуть на урон (не более базового бонуса атаки)</td></tr>
<tr><td><a href="feats/cleave.html">Рассечение</a></td><td>power-attack</td><td>Дополнительная атака бл. боя после падения противника</td></tr>
<tr><td><a href="feats/great-cleave.html">Исключительное рассечение</a></td><td>cleave, power-attack, base attack bonus +4</td><td>Нет ограничений на количество рассечений в раунд</td></tr>
<tr><td><a href="feats/improved-bull-rush.html">Улучшенный натиск</a></td><td>power-attack</td><td>+4 к попытке оттолкнуть противника; без атаки при возможности</td></tr>
<tr><td><a href="feats/improved-overrun.html">Улучш. прорыв</a></td><td>power-attack</td><td>+4 при попытке свалить противника наземь; без атаки при возможности</td></tr>
<tr><td><a href="feats/improved-sunder.html">Улучш. удар по оружию</a></td><td>power-attack</td><td>+4 к попыткам освободиться от захвата; без атаки при возмож.</td></tr>
<tr><td><a href="feats/quick-draw.html">Выхватить оружие</a></td><td>Base attack bonus +1</td><td>Доставание оружия как свободное действие</td></tr>
<tr><td><a href="feats/rapid-reload.html">Быстрая перезарядка</a></td><td>Weapon Proficiency with crossbow</td><td>Перезарядка арбалета ускорена</td></tr>
<tr><td><a href="feats/run.html">Бег</a></td><td></td><td>Бег со скорость, в 5 раз больше нормальной, +4 к Прыжкам (с разбега)</td></tr>
<tr><td><a href="feats/self-sufficient.html">Самостоятельность</a></td><td></td><td>+2 к Лечению и Выживанию</td></tr>
<tr><td><a href="feats/shield-proficiency.html">Владение щитом</a></td><td></td><td>Нет штрафа за ношение доспеха и при атаке</td></tr>
<tr><td><a href="feats/improved-shield-bash.html">Улучш. удар щитом</a></td><td>shield-proficiency</td><td>??</td></tr>
<tr><td><a href="feats/tower-shield-proficiency.html">Владение башенным щитом</a></td><td>shield-proficiency</td><td>??</td></tr>
<tr><td><a href="feats/simple-weapon-proficiency.html">Владение простым оружием</a></td><td></td><td>??</td></tr>
<tr><td><a href="feats/skill-focus.html">Концентрация на умении</a></td><td></td><td>??</td></tr>
<tr><td><a href="feats/spell-focus.html">Концентрация на заклинании</a></td><td></td><td>+1 к УС спасбр. против закли-нания определенной школы</td></tr>
<tr><td><a href="feats/greater-spell-focus.html">Искл. концен. на заклинании</a></td><td></td><td>+1 к УС спасбр. против закли-нания определенной школы</td></tr>
<tr><td><a href="feats/spell-mastery.html">Мастерство заклинателя</a></td><td>Wizard level 1st</td><td>Может готовить некоторые за-клинания без книги заклинаний</td></tr>
<tr><td><a href="feats/spell-penetration.html">Проникновение заклинания</a></td><td></td><td>+2 к проверке уровня заклина-теля при противостоянии заклинанию</td></tr>
<tr><td><a href="feats/greater-spell-penetration.html">Искл. проникновение заклинания</a></td><td>spell-penetration</td><td>+4 к проверке уровня заклина-теля при противостоянии заклинанию</td></tr>
<tr><td><a href="feats/stealthy.html">Скрытность</a></td><td></td><td>+2 к умениям Прятаться и Бесшумное Передвижение</td></tr>
<tr><td><a href="feats/toughness.html">Крепкость</a></td><td></td><td>+3 хит поинта</td></tr>
<tr><td><a href="feats/track.html">Выслеживание</a></td><td></td><td>Использ. умение Выживание для поиска следов</td></tr>
<tr><td><a href="feats/two-weapon-fighting.html">Бой с оружием в обеих руках</a></td><td>Dex 15</td><td>Уменьшает штраф при исполь-зовании двух оружий на 2</td></tr>
<tr><td><a href="feats/two-weapon-defense.html">Защита с оружием в обеих руках</a></td><td>two-weapon-fighting</td><td>Второе оруж. дает бонус щита +1 к КЗ</td></tr>
<tr><td><a href="feats/improved-two-weapon-fighting.html">Улучш. бой с оружием в обеих руках</a></td><td>Dex 17, two-weapon-fighting, base attack bonus +6</td><td>Дает вторую атаку вторым оружием</td></tr>
<tr><td><a href="feats/greater-two-weapon-fighting.html">Искл. бой с оружием в обеих руках</a></td><td>Dex 19, improved-two-weapon-fighting, two-weapon-fighting, base attack bonus +11</td><td>Дает третью атаку вторым оружием</td></tr>
<tr><td><a href="feats/weapon-finesse.html">Фехтование легким оружием</a></td><td>Proficiency with weapon, base attack bonus +1</td><td>Использование модификатора Ловкости вместо модификатора Силы при использовании легкого оружия ближнего боя</td></tr>
<tr><td><a href="feats/weapon-focus.html">Концентрация на оружии</a></td><td>Proficiency with weapon, base attack bonus +1</td><td>+1 к атаке выбранным оружием</td></tr>
<tr><td><a href="feats/weapon-specialization.html">Специализация на оружии</a></td><td>Proficiency with weapon, weapon-focus, fighter level 4th</td><td>+2 к урону выбранным оружием</td></tr>
<tr><td><a href="feats/greater-weapon-focus.html">Искл. концентр. на оружии</a></td><td>Proficiency with weapon, weapon-focus, fighter level 8th</td><td>+2 к атаке выбранным оружием</td></tr>
<tr><td><a href="feats/greater-weapon-specialization.html">Искл. специал. на оружии</a></td><td>Proficiency with weapon, greater-weapon-focus, weapon-focus, weapon-specialization, fighter level 12th</td><td>+4 к урону выбранным оружием</td></tr> <tr><th colspan="3">Навыки Создания Предметов</th></tr> <tr><td><a href="feats/brew-potion.html">Сварить зелье</a></td><td>Spellcaster level 3rd</td><td>Сварить зелье</td></tr>
<tr><td><a href="feats/craft-magic-arms-and-armor.html">Изготовление магического оружия или доспеха</a></td><td>Spellcaster level 5th</td><td>Изготовление магического оружия или доспеха</td></tr>
<tr><td><a href="feats/craft-rod.html">Изготовление жезла</a></td><td>Spellcaster level 9th</td><td>Изготовление жезла</td></tr>
<tr><td><a href="feats/craft-staff.html">Изготовление посоха</a></td><td>Spellcaster level 12th</td><td>Изготовление посоха</td></tr>
<tr><td><a href="feats/craft-wand.html">Изготовление волшебной палочки</a></td><td>Spellcaster level 5th</td><td>Изготовление волшебной палочки</td></tr>
<tr><td><a href="feats/craft-wondrous-item.html">Изготовление чудесного предмета</a></td><td>Spellcaster level 3rd</td><td>Изготовление чудесного предмета</td></tr>
<tr><td><a href="feats/forge-ring.html">Ковка колец</a></td><td>Spellcaster level 12th</td><td>Ковка колец</td></tr>
<tr><td><a href="feats/scribe-scroll.html">Написать свиток</a></td><td>Spellcaster level 1st</td><td>Написать свиток</td></tr> <tr><th colspan="3">Метамагические навыки</th></tr> <tr><td><a href="feats/empower-spell.html">Усилить заклинание</a></td><td></td><td>Увеличить количество, варианты эффектов на 50%</td></tr>
<tr><td><a href="feats/enlarge-spell.html">Удлинить заклинание</a></td><td></td><td>Удвоить дистанцию</td></tr>
<tr><td><a href="feats/extend-spell.html">Продлить заклинание</a></td><td></td><td>Удвоить продолжительность</td></tr>
<tr><td><a href="feats/heighten-spell.html">Повысить уровень заклинания</a></td><td></td><td>Кастануть заклинание, будто оно более высокого уровня</td></tr>
<tr><td><a href="feats/maximize-spell.html">Максимизировать заклинание</a></td><td></td><td>Максимизировать эффект</td></tr>
<tr><td><a href="feats/quicken-spell.html">Ускорить заклинание</a></td><td></td><td>Кастование как свободное действие</td></tr>
<tr><td><a href="feats/silent-spell.html">Безмолвное заклинание</a></td><td></td><td>Кастовать без произнесения вербального компонента</td></tr>
<tr><td><a href="feats/still-spell.html">Недвижное заклинание</a></td><td></td><td>Кастовать без соматического компонента</td></tr>
<tr><td><a href="feats/widen-spell.html">Расширить заклинание</a></td><td></td><td>Удвоить зону действия</td></tr>
</table>
`